'''
Due to me experiencing problems with high demand on the server side of the API, I will
be using a script generated by AI that tries to run the functions multiple times at
different times, with an increasing gap between the attempts
'''

'''
This is my original code:

import llm

model = llm.get_model("gemini-3.8-flash")


# Function to generate the python script using the full prompt
def create_script_full(model, prompt):
    response = model.prompt(prompt)
    return response.text(), response.usage()


# Function to generate the python script using step by step prompts
def create_script_steps(model, prompts):
    # Storing the history of the prompts
    conversation = model.conversation()
    responses = []
    # Iterate through each prompt
    for prompt in prompts:
        response = conversation.prompt(prompt)
        responses.append((response.text(), response.usage()))
    return responses


full_prompt = "Write a Python function below_zero(ops). ops is a list of ints representing deposits and withdrawals on a bank account that starts with a balance of 0. Detect if at any point the balance goes below 0; if so return True, otherwise return False."

step_by_step = [
    "Write me a function below_zero to find out if an account ever goes below 0.",
    "The input's a list of ints representing transactions.",
    "The balance starts at 0.",
    "Return True if the balance ever goes below 0, otherwise False."
]

# print(create_script_full(model, full_prompt))

print(create_script_steps(model, step_by_step))
'''

'''
This is the code generated by AI using my code as a base:
'''

import time

import llm

model = llm.get_model("gemini-3.6-flash")


# Retry a call when the API reports a temporary error (e.g. "high demand")
def with_retry(fn, max_attempts=6, base_delay=5):
    for attempt in range(1, max_attempts + 1):
        try:
            return fn()
        except llm.ModelError as e:
            # Only retry temporary errors; fail right away on things like a bad key
            temporary = any(
                hint in str(e).lower()
                for hint in ("high demand", "overloaded", "unavailable", "try again")
            )
            if attempt == max_attempts or not temporary:
                raise
            delay = base_delay * 2 ** (attempt - 1)  # 5s, 10s, 20s, ...
            print(f"Attempt {attempt} failed: {e}\nRetrying in {delay}s...")
            time.sleep(delay)


# Function to generate the python script using the full prompt
def create_script_full(model, prompt):
    def attempt():
        response = model.prompt(prompt)
        return response.text(), response.usage()  # text() is what sends the request

    return with_retry(attempt)


# Function to generate the python script using step by step prompts
def create_script_steps(model, prompts):
    def attempt():
        # Storing the history of the prompts
        conversation = model.conversation()
        responses = []
        # Iterate through each prompt
        for prompt in prompts:
            response = conversation.prompt(prompt)
            responses.append((response.text(), response.usage()))
        return responses

    # If any step fails, the whole conversation restarts from step 1
    return with_retry(attempt)


full_prompt = "Write a Python function below_zero(ops). ops is a list of ints representing deposits and withdrawals on a bank account that starts with a balance of 0. Detect if at any point the balance goes below 0; if so return True, otherwise return False."

step_by_step = [
    "Write me a function below_zero to find out if an account ever goes below 0.",
    "The input's a list of ints representing transactions.",
    "The balance starts at 0.",
    "Return True if the balance ever goes below 0, otherwise False.",
]

print(create_script_full(model, full_prompt))

# print(create_script_steps(model, step_by_step))
